"""Dataset assembly and split helpers for OPTI-MED modeling work."""

from opti_med.modeling.first_scope_baseline import (
    FIRST_SCOPE_BASELINE_ARTIFACT_VERSION,
    FirstScopeBaselineRunResult,
    FirstScopeBaselineSupervisedData,
    build_first_scope_baseline_report,
    build_first_scope_baseline_supervised_data,
    load_first_scope_baseline_inputs,
    run_first_scope_baseline,
    write_first_scope_baseline_artifacts,
)
from opti_med.modeling.first_scope_dataset import (
    CANONICAL_TRAINING_FILTER,
    FIRST_SCOPE_DATASET_CONTRACT_VERSION,
    FIRST_SCOPE_SPLITS_CONTRACT_VERSION,
    DATASET_KEY_COLUMNS,
    FirstScopeDatasetBuildResult,
    StableSubjectSplitGenerator,
    build_first_scope_dataset,
    build_first_scope_dataset_qc_report,
    build_first_scope_feature_list,
    build_first_scope_splits,
    calculate_first_scope_dataset_qc_metrics,
    derive_trainable_feature_columns,
    select_benchmark_columns_from_dataset,
    select_label_columns_from_dataset,
    select_meta_columns_from_dataset,
    select_trainable_feature_columns_from_dataset,
    summarize_first_scope_dataset,
    validate_first_scope_dataset_artifact,
    validate_first_scope_split_artifact,
    write_first_scope_dataset_qc_report,
)

__all__ = [
    "FIRST_SCOPE_BASELINE_ARTIFACT_VERSION",
    "FIRST_SCOPE_DATASET_CONTRACT_VERSION",
    "FIRST_SCOPE_SPLITS_CONTRACT_VERSION",
    "CANONICAL_TRAINING_FILTER",
    "DATASET_KEY_COLUMNS",
    "FirstScopeBaselineRunResult",
    "FirstScopeBaselineSupervisedData",
    "FirstScopeDatasetBuildResult",
    "StableSubjectSplitGenerator",
    "build_first_scope_baseline_report",
    "build_first_scope_baseline_supervised_data",
    "build_first_scope_dataset",
    "build_first_scope_dataset_qc_report",
    "build_first_scope_feature_list",
    "build_first_scope_splits",
    "calculate_first_scope_dataset_qc_metrics",
    "derive_trainable_feature_columns",
    "load_first_scope_baseline_inputs",
    "run_first_scope_baseline",
    "select_benchmark_columns_from_dataset",
    "select_label_columns_from_dataset",
    "select_meta_columns_from_dataset",
    "select_trainable_feature_columns_from_dataset",
    "summarize_first_scope_dataset",
    "validate_first_scope_dataset_artifact",
    "validate_first_scope_split_artifact",
    "write_first_scope_dataset_qc_report",
    "write_first_scope_baseline_artifacts",
]
